[package]
name = "odt"
version = "0.1.0"
edition = "2021"
default-run = "dtc"

[dependencies]
hashlink = "0.9.1"
pest = "2.7.15"
pest_derive = { version = "2.7.15", features = ["grammar-extras"] }
pest_typed = "0.16.0"
pest_typed_derive = { version = "0.16.0", features = ["grammar-extras"] }
clap = { version = "4.5.21", features = ["derive"] }

[features]
wrapping-arithmetic = []

[[bin]]
name = "dtc"

[[bin]]
name = "dtsfmt"

[[bin]]
name = "genexpr"

[dev-dependencies]
pretty_assertions = "1.4.1"

[profile.release]
debug = true

