[package]
name = "dtsp"
version = "0.1.0"
edition = "2021"

[dependencies]
hashlink = "0.9.1"
pest = "2.7.14"
pest_derive = "2.7.14"
pest_typed = "0.16.0"
pest_typed_derive = "0.16.0"
clap = { version = "4.5.21", features = ["derive"], optional = true }

[[bin]]
name = "dtc"
required-features = ["clap"]

[[bin]]
name = "dtsfmt"

[[bin]]
name = "genexpr"

[dev-dependencies]
pretty_assertions = "1.4.1"
